language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
install:
    pip install coveralls

before_script:
  - '[ "${TRAVIS_PYTHON_VERSION}" = "2.6" ] && pip install --use-mirrors unittest2 || /bin/true'
script:
    coverage run --source=gitshelve setup.py test
after_success:
    coveralls
